apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cvat-db
  name: cvat-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cvat-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: cvat
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_USER
              value: root
          image: postgres:15-alpine
          name: cvat-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: cvat-db
      restartPolicy: Always
      volumes:
        - name: cvat-db
          persistentVolumeClaim:
            claimName: cvat-db
