apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cvat-redis-inmem
  name: cvat-redis-inmem
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-redis-inmem
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cvat-redis-inmem
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "60"
            - "100"
            - --appendonly
            - "yes"
          image: redis:7.2.3-alpine
          name: cvat-redis-inmem
          volumeMounts:
            - mountPath: /data
              name: cvat-inmem-db
      restartPolicy: Always
      volumes:
        - name: cvat-inmem-db
          persistentVolumeClaim:
            claimName: cvat-inmem-db
