apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
    traefik.enable: "true"
    traefik.http.routers.cvat-ui.entrypoints: web
    traefik.http.routers.cvat-ui.rule: Host(`localhost`)
    traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
  labels:
    io.kompose.service: cvat-ui
  name: cvat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-ui
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
        traefik.enable: "true"
        traefik.http.routers.cvat-ui.entrypoints: web
        traefik.http.routers.cvat-ui.rule: Host(`localhost`)
        traefik.http.services.cvat-ui.loadbalancer.server.port: "80"
      labels:
        io.kompose.service: cvat-ui
    spec:
      containers:
        - image: cvat/ui:dev
          name: cvat-ui
      restartPolicy: Always
