apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cvat-opa
  name: cvat-opa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cvat-opa
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cvat-opa
    spec:
      containers:
        - args:
            - run
            - --server
            - --log-level=error
            - --set=services.cvat.url=http://cvat-server:8080
            - --set=bundles.cvat.service=cvat
            - --set=bundles.cvat.resource=/api/auth/rules
            - --set=bundles.cvat.polling.min_delay_seconds=5
            - --set=bundles.cvat.polling.max_delay_seconds=15
          image: openpolicyagent/opa:0.63.0
          name: cvat-opa
      restartPolicy: Always
