services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python -m gunicorn cvat.asgi:application --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
    # volumes:
    #   - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: cvat_db
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: root
      # POSTGRES_PASSWORD: 
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data: