x-backend-env: &backend-env
  CVAT_POSTGRES_HOST: cvat
  CVAT_REDIS_INMEM_HOST: cvat_redis_inmem
  CVAT_REDIS_INMEM_PORT: 6379
  CVAT_REDIS_ONDISK_HOST: cvat_redis_ondisk
  CVAT_REDIS_ONDISK_PORT: 6666
  CVAT_LOG_IMPORT_ERRORS: 'true'
  DJANGO_LOG_SERVER_HOST: vector
  DJANGO_LOG_SERVER_PORT: 80
  SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:-}

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

  cvat_redis_inmem:
    container_name: cvat_redis_inmem
    image: redis:7.2.3-alpine
    restart: always
    command: ["redis-server", "--save", "60", "100", "--appendonly", "yes"]
    volumes:
      - cvat_inmem_db:/data
    networks:
      - cvat

  cvat_redis_ondisk:
    container_name: cvat_redis_ondisk
    image: apache/kvrocks:2.7.0
    restart: always
    command: ["--dir", "/var/lib/kvrocks/data"]
    volumes:
      - cvat_ondisk_db:/var/lib/kvrocks/data
    networks:
      - cvat

  cvat_server:
    container_name: cvat
    image: cvat/server:latest
    restart: always
    depends_on:
      - cvat_db
      - cvat_redis_inmem
      - cvat_redis_ondisk
    environment:
      <<: *backend-env
    command: init run server
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_ui:
    container_name: cvat_ui
    image: cvat/ui:latest
    restart: always
    depends_on:
      - cvat_server
    environment:
      REACT_APP_API_URL: 'http://localhost:8080/api/v1'
    ports:
      - "3000:80"
    networks:
      - cvat

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_inmem_db:
  cvat_ondisk_db:

networks:
  cvat:
