apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    io.kompose.service: traefik
