apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traefik
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\cmpia\Documents\2024 Summer\deploycvat\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: traefik
    spec:
      containers:
        - env:
            - name: CVAT_HOST
              value: localhost
            - name: DJANGO_LOG_VIEWER_HOST
              value: grafana
            - name: DJANGO_LOG_VIEWER_PORT
              value: "3000"
            - name: TRAEFIK_ACCESSLOG_FORMAT
              value: json
            - name: TRAEFIK_ENTRYPOINTS_web_ADDRESS
              value: :8080
            - name: TRAEFIK_LOG_FORMAT
              value: json
            - name: TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT
              value: "false"
            - name: TRAEFIK_PROVIDERS_DOCKER_NETWORK
              value: cvat
            - name: TRAEFIK_PROVIDERS_FILE_DIRECTORY
              value: /etc/traefik/rules
          image: traefik:v2.10
          name: traefik
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
